### PR TITLE
suse2020 rebrand

### PR DESCRIPTION
**Pull request by sknorr**
* Add a rebranded version of suse2013 as suse2020 (notably, a bit WIP and not yet actually ship-ready)
* Remove lots of things we don't really ship
* Update Makefile etc.

Unfortunately, while these are somewhat different things, I can't really split all of them out (or at least it would be a bit of a waste of time).

### CODE REVIEW

**Comment by sknorr** [comment]
@tomschr Okay, soo:

* I went ahead and already merged everything that had to do with the cleanups.
* I did the namespacing, Makefiling, etc. for the new namespace-only stylesheets as you suggested. However, these are still in separate commits, so if you do decide that you'd rather cancel your conversion activity of the SLE 11 stuff, we can still do that by just removing a bunch of commits.

**Comment by tomschr** [comment]
@sknorr Thanks a million, Stefan! :heart: :+1: 

I've started with the conversion for SLE11SP4 and English: SUSE/doc-sle-legacy#4

**Comment by sknorr** [comment]
We probably need to put this on hold for ~a month until we know what we get in terms of a suse.com redesign.

**Comment by sknorr** [comment]
This can be closed. The then-new branding is now outdated.

**Pull request closed without merging**
