### PR TITLE
version.xsl -> VERSION, added link VERSION.xsl

### PR DESCRIPTION
**Pull request by tomschr**
Also adapt fo and xhtml stylesheets
Related to https://github.com/openSUSE/daps/pull/358

@sknorr Please review

### CODE REVIEW

**Comment by sknorr** [comment]
Looking good, but can you do the same for the `suse` dir?

**Comment by tomschr** [comment]
@sknorr See commit 6aa46d3

**Comment by sknorr** [comment]
Mm... Okay, but this is probably referenced from the `suse` stylesheets in the same way is it is references in the `suse2013` ones.

**Comment by tomschr** [comment]
Yes, I've changed it in the meantime. See commit 5528adf

**Comment by sknorr** [comment]
Thanks!

**Pull request merged**
