### PR TITLE
Packaging: revert to liberation-fonts

### PR DESCRIPTION
**Pull request by DimStar77**
liberation2-fonts was an attempt to make things better, but reality looks different
[bsc#1077375] [rh#856239]

### CODE REVIEW

**Comment by DimStar77** [comment]
liberation2-fonts is scheduled for removal from openSUSE : https://build.opensuse.org/request/show/568893

**Comment by pgajdos** [comment]
Thanks Dominique.

**Comment by sknorr** [comment]
Thanks! Merged.

**Comment by sknorr** [comment]
One question: Do we need to submit a new package version immediately now or what is the time frame for you people?

**Comment by DimStar77** [comment]
asap would be nice so that liberation2-fonts could be removed from SLE15/Leap15 before we hit the point when removals are getting tricky

**Pull request merged**
